// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zecnturxqoisahnvstuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplY250dXJ4cW9pc2FobnZzdHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODY2NTQsImV4cCI6MjA2MzY2MjY1NH0.iTOKrbrz--aLquBec4RQpaGsbw9IH8quCHxe1GU3vlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);